### ISSUE TITLE
Configure e-mail box for SES 

### ISSUE THREAD

**Issue by OtisRed** [CodeForPoznan/codeforpoznan.pl_v3#120]
**General description**
1. Given that we deploy our app on AWS we need to use native services to get e-mails from the website. 
1. Also it would be nice to catch e-mails when app is run in docker to test delivery locally. 

**Technical description**
Use Simple Email Service in AWS to send and receive e-mails

1. Create a bucket for e-mails
1. Create a queque in SES
1. Link the two together 
1. Create policies 

**Support documentation**
https://aws.amazon.com/premiumsupport/knowledge-center/ses-receive-inbound-emails/

**Comment by OtisRed** [comment]
@jacekkalbarczyk Jacek can  you take it?

**Comment by OtisRed** [comment]
**Possible solutions**
1. Using SES shoudln't be an issue given that we already have it in the infrastructure
2. One of the solutions is to import SES from Boto: https://www.learnaws.org/2020/12/18/aws-ses-boto3-guide/ 
3. Bucket is needed only if we assume we want to test sending e-mails - if don't we can disregard it

**Comment by arturtamborski** [comment]
Some explanation of the S3 bucket thingy - originally I had an idea where we'd use s3 bucket for storing mails from `dev` domain for debugging, but actually send the mails from the `prod` domain. This would allow us to test the mail form without spamming `hello@` with debug mails. Technically it's not required, because we can hardcode sending mails to `hello@` in both domains and just deal with the spam in other way (gmail filters?), but yeah, it's not required.

The only required thing here to do is to enable SES endpoint so that we can send mail from backend, that's all.

Now, on how to actually send the mail there are three approaches:
1. Send it via raw HTTP requests - not recommended, tricky to get right
2. Send mails with `boto3` (aws library) - super easy to get working
3. Send mails with `flask-mail` via SMTP protocol - more complicated than [2], still doable and useful if we would want to use other SMTP provider.

Last thing I want to talk about is debugging the mails from `dev` domain. It's surprisingly tricky, because access to `hello@` is restricted and that's where the mails should go so it's either spamming your mailbox or creating temp mails or... we could use a service focused on testing the mails! :) https://ethereal.email/
They offer a free way of sending mails to their server which will then give us a pretty link where we can inspect the resulting message without it being actually sent (by mistake or intentionally). I'd want to enable this service for any mail-sending situations where it's _not_ production. In other words, I'd like to use this mail-capturing service for localhost, dev or any other environment which is not production.

What do you think?
