### ISSUE TITLE
Contact form for stakeholders

### ISSUE THREAD

**Issue by MargoWM** [CodeForPoznan/codeforpoznan.pl_v3#281]
This ticket replaces #28.
We need to discuss the contact form for stakeholders/ NGOs/clients.

**Comment by magul** [comment]
I guess you mixing here two things:
 * list of projects on our website - we agreed on a refinement call, that we will store them in JSON in GitHub and they will be rendered from there (so no DB involved)
 * contact form dedicated to NGOs/clients/stakeholders to share with us ideas about new projects, that we can be involved into (here my suggestion for now, as I anticipate low volume of messages here, that we can settle with sending such information into _hello@codeforpoznan.pl_ email account instead of creating the whole dedicated system to maintain such inqueires in our website).

**Comment by MargoWM** [comment]
I am not mixing. Ticket #28 was consist of two parts which we discussed yesterday.
The first one was adding/editing projects. And we agreed that JSON will be a better option than DB. Because of that, we closed ticket #28 and tickets from #252 to #263.
The second thing which we discussing yesterday with these tickets was the possibility of adding new projects for new stakeholders. 
Summarizing we need to discuss the form of contact with NGOs/clients/stakeholders and wait for UX opinion. For that reason, I created this ticket.

**Comment by magul** [comment]
But that are totally two different topics (and that's from POV it's a mix):

> The first one was adding/editing projects. And we agreed that JSON will be a better option than DB.

> discuss the form of contact with NGOs/clients/stakeholders 

In the title of the ticket is `Contact form...` so I would assume that it's about later, but in the description you mention `All of the changes will be created in JSON in GitHub repo.` which is connected with the first one.

I'm confused. Which one we're talking about:
 * list of projects on our website (rendered from JSON)
 * contact form for potential clients?

We shouldn't discuss both here...

**Comment by magul** [comment]
(or the JSON part in the description was just put there by mistake and that causes my confusion?, btw #28 also contains that mix, but we should clarify that and make separate tickets for both of these topics)

**Comment by OtisRed** [comment]
This idea was discarded some time ago. Both organizations and volunteers can use the same contact from for now.
