### ISSUE TITLE
Static link for Slack invite

### ISSUE THREAD

**Issue by ad-m** [CodeForPoznan/codeforpoznan.pl_v3#310]
#### Subject of the issue:

Na https://github.com/CodeForPoznan/codeforpoznan.pl_v3/blob/dcf96063d20acacea850820087719b1ac057872f/frontend/src/components/SocialMedia.vue mamy link do Slacka. Jest to długi link wobec, którego istnieje ryzyko zmiany. Wolałbym, aby powstał w ramach tej strony link z przekierowaniem, który będzie stały i będzie okresowo weryfikowany w zakresie poprawności.

#### Your environment:

Linux

#### Steps to reproduce:

NA

#### Actual behaviour:

Długi link w stopce

#### Expected behaviour:

Krótki link w stopce
Nowa podstrona z przekierowaniem

**Comment by OtisRed** [comment]
@ad-m dzięki za input! Przegadamy to przy najbliższej okazji

**Comment by OtisRed** [comment]
Given that slack introduced static invite links this is no longer a risk, thus there's no need to automate some procedure that checks the link. It also doesn't make sense to shorten it because it introduces another layer of abstracting in processing data for something that is constant and could be easily compared to the root link on slack.
